feat: Guardians can propose, cast votes and execute a freeze/key rotation operation through their view
nymlab/vectis_fe pull request #22
Opened 2022-05-27 09:03 UTC by giovanni-orciuolo

The flow goes like this: when a wallet is multisig, a guardian can propose an operation. When a proposal is made, the guardian who proposed it automatically casts a "yes" vote for it. The other guardians can then come to the page and vote for the proposal ("yes", "no" or "abstain"). If the proposal reaches a number of positive votes greater than or equal to the defined threshold for the wallet, then the proposal can be executed. This is done manually by one of the guardians, it doesn't matter who does it, by clicking on the passed proposal in the view. It is always possible to see the status of a proposal, and the list of casted votes.

2022-05-27 16:13 UTC, j0nl1 requested changes
I think in general we could reduce complexity, doing components smaller.

For example the function groupVoteListByVote there is no need to live in ProposalDetailsModal, it will make the component more simple and also it don't have to re-render that function anymore. 

If a component is re-render all the content inside the component are rendering included functions, not just html nodes.

Another example will be HTML complexity, in the same component we have these nodes:
```jsx
<div className="flex items-center w-full justify-around mb-2">
                      <p className="text-green-600">YES: {groupVoteListByVote(voteList, "yes").weight}</p>
                      <p className="text-red-600">NO: {groupVoteListByVote(voteList, "no").weight}</p>
                      <p className="text-gray-600">ABSTAIN: {groupVoteListByVote(voteList, "abstain").weight}</p>
                    </div>
```

I think that could be a small component which receive a voteList.

These suggestions don't have to be changed now, just to keep it in mind for the future.

2022-05-30 07:38 UTC, giovanni-orciuolo commented on services/vectis.ts
> +  let title = "",
Done in [`3102eca` (#22)](https://github.com/nymlab/vectis_fe/pull/22/commits/3102ecaca3ca9656c41e40b80d445f6df44fa57b)

2022-05-30 07:40 UTC, j0nl1 commented on services/vectis.ts
> +  let title = "",
awesome!! 🙌

2022-05-30 08:06 UTC, giovanni-orciuolo commented
@j0nl1 In [`67a4d32` (#22)](https://github.com/nymlab/vectis_fe/pull/22/commits/67a4d3243aa2eb17c674315f94918b63c15a68c7) I made a Modal component which we can reuse to create a modal. I plan to later separate the modal children into separate components so we can use them without them being in a modal (more separation of concerns)

2022-05-30 08:11 UTC, giovanni-orciuolo commented on components/modals/ProposalDetailsModal.tsx
> +                {voteList?.length > 0 && (
Done in [`31933d3` (#22)](https://github.com/nymlab/vectis_fe/pull/22/commits/31933d32845fcac77487052ff137b1822dcef42d)

2022-05-30 08:30 UTC, giovanni-orciuolo commented on components/buttons/FreezeButton.tsx
> +            alreadyVoted ? "btn-disabled" : "btn-primary"
This check is already present in the `openVoteModal()` functions https://github.com/nymlab/vectis_fe/blob/feat/multisig-voting/components/buttons/FreezeButton.tsx#L91 (same in `RotateKeyButton`)

2022-05-30 08:30 UTC, giovanni-orciuolo commented on components/buttons/RotateKeyButton.tsx
> +            alreadyVoted ? "btn-disabled" : "btn-primary"
This check is already present in the `openVoteModal()` functions https://github.com/nymlab/vectis_fe/blob/feat/multisig-voting/components/buttons/FreezeButton.tsx#L91 (same in `RotateKeyButton`)

2022-05-30 08:39 UTC, giovanni-orciuolo commented on components/GuardianView.tsx
> +            {getWalletFreezeProposal() && (
Done in [`6f3fbde` (#22)](https://github.com/nymlab/vectis_fe/pull/22/commits/6f3fbde032bcef6bea547e08632b9f06cf57291a)

2022-05-30 08:45 UTC, whalelephant commented
I have tested the workflow it woks well.

2022-05-30 08:45 UTC, whalelephant approved these changes

2022-05-31 07:22 UTC, j0nl1 approved these changes

2022-05-31 07:22 UTC, merged